-- Бренд-киты и черновики контент-стратегий, 29.09.2026 (сгенерировано scripts/brand_kits_2026-09-29.py)
-- Бренд: перезаписывается только у карточек, где бренда ещё нет (Госпожу Елю и Марию не трогаем).
-- Стратегия: добавляется только там, где текущей стратегии ещё нет.

insert into public.client_brand (client_id, kit, version) values (13, $q${"identity": {"display_name": "Дмитрий Иванов", "role_line": "тренер по паделу", "niche": "sport", "geo": "уточнить", "language": "ru", "address": "ты", "voice_notes": "Тренер объясняет на пальцах: одна ошибка или приём за ролик, сразу показ на корте. Коротко, энергично, с долей юмора («наше детство»).", "words_yes": ["упражнение", "ошибка новичков", "смотри", "на корте"], "words_no": []}, "visual": {"colors": {"bg": "#0E1A2B", "bg_alt": "#F4F6F8", "text": "#FFFFFF", "text_on_light": "#111111", "accent": "#39FF3A", "muted": "#AEB6C2", "card": "rgba(0,0,0,.55)", "court": "#1E5BD8", "stroke": "#000000"}, "fonts": {"display": {"family": "Oswald", "source": "google", "weight": 700, "case": "upper"}, "accent": {"family": "Oswald", "source": "google", "weight": 700, "case": "upper"}, "body": {"family": "Oswald", "source": "google", "weight": 600, "case": "upper"}}, "photo_style": "крытый падел-корт, синее покрытие; тренер в белой футболке с петличкой, ракетка в руках", "layout": ["сплит: сверху игра или профи-матч, снизу тренер в кадр по пояс", "хук-заголовок узким капсом по центру верхней половины, белый или неоново-зелёный с чёрной обводкой", "цифра-хук крупно неоновым («28700€»)", "субтитры по одному слову по центру, белый капс с обводкой", "круглый логотип клуба в углу"], "shape": {"radius": "0 — плашек нет, только обводка текста"}}, "channels": {"instagram": "https://instagram.com/ivanovsport", "cta_style": "уточнить"}, "rules": {"compliance": "standard", "never": [], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (14, $q${"identity": {"display_name": "Іван Панченко", "role_line": "пластичний хірург", "niche": "medical", "geo": "Україна", "language": "uk", "address": "вы", "voice_notes": "Експертно, з чіпким хуком-твердженням, а не питанням. Заперечення очевидного («Ні, це не мама і донька…»), далі масштаб на глядача. Лікар іноді ВІДМОВЛЯЄ — це сильніше за рекламу.", "words_yes": ["ваш випадок", "розберемо", "як лікар", "результат"], "words_no": ["гарантую", "без ризиків", "назва процедури в заголовку"]}, "visual": {"colors": {"bg": "#1A1A1C", "bg_alt": "#F2F2F2", "text": "#FFFFFF", "text_on_light": "#111111", "accent": "#F5D90A", "muted": "#9A9A9A", "card": "rgba(0,0,0,.6)", "alert": "#E53935"}, "fonts": {"display": {"family": "Oswald", "source": "google", "weight": 700, "case": "upper"}, "accent": {"family": "Oswald", "source": "google", "weight": 700, "case": "upper"}, "body": {"family": "PT Serif", "source": "google", "weight": 400, "case": "normal"}}, "photo_style": "темна студія, подкаст-мікрофон; лікар у тій самій формі (синій скраб або темний светр) по центру", "layout": ["дисклеймер зверху дрібним курсивом: «Відео має інформаційний характер. Необхідна консультація фахівця.»", "обкладинка: спліт — об'єкт розмови по краях, лікар у центрі, жирний білий гротеск капсом 2–3 рядки", "субтитри білою антиквою, ключові слова жовтим вузьким капсом", "вставки: операційна, 3D-анатомія, до/після"], "shape": {"radius": "0"}}, "channels": {"instagram": "https://instagram.com/dr.panch", "cta_style": "IG: «+» в коментарях; TikTok: у директ. «Розберемо ваш випадок»"}, "rules": {"compliance": "medical", "never": ["гарантований результат", "назва процедури як заголовок обкладинки"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (15, $q${"identity": {"display_name": "Іван Панченко", "role_line": "пластичний хірург", "niche": "medical", "geo": "Україна", "language": "uk", "address": "вы", "voice_notes": "Експертно, з чіпким хуком-твердженням, а не питанням. Заперечення очевидного («Ні, це не мама і донька…»), далі масштаб на глядача. Лікар іноді ВІДМОВЛЯЄ — це сильніше за рекламу.", "words_yes": ["ваш випадок", "розберемо", "як лікар", "результат"], "words_no": ["гарантую", "без ризиків", "назва процедури в заголовку"]}, "visual": {"colors": {"bg": "#1A1A1C", "bg_alt": "#F2F2F2", "text": "#FFFFFF", "text_on_light": "#111111", "accent": "#F5D90A", "muted": "#9A9A9A", "card": "rgba(0,0,0,.6)", "alert": "#E53935"}, "fonts": {"display": {"family": "Oswald", "source": "google", "weight": 700, "case": "upper"}, "accent": {"family": "Oswald", "source": "google", "weight": 700, "case": "upper"}, "body": {"family": "PT Serif", "source": "google", "weight": 400, "case": "normal"}}, "photo_style": "темна студія, подкаст-мікрофон; лікар у тій самій формі (синій скраб або темний светр) по центру", "layout": ["дисклеймер зверху дрібним курсивом: «Відео має інформаційний характер. Необхідна консультація фахівця.»", "обкладинка: спліт — об'єкт розмови по краях, лікар у центрі, жирний білий гротеск капсом 2–3 рядки", "субтитри білою антиквою, ключові слова жовтим вузьким капсом", "вставки: операційна, 3D-анатомія, до/після"], "shape": {"radius": "0"}}, "channels": {"instagram": "https://instagram.com/dr.panch", "cta_style": "IG: «+» в коментарях; TikTok: у директ. «Розберемо ваш випадок»"}, "rules": {"compliance": "medical", "never": ["гарантований результат", "назва процедури як заголовок обкладинки"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (21, $q${"identity": {"display_name": "Olena Hart", "role_line": "коуч · трансформационные игры", "niche": "expert", "geo": "Нью-Йорк, онлайн", "language": "ru", "address": "ты", "voice_notes": "Тёплый, женский, поддерживающий, но уверенный. Деньги и самоценность через игру — живой опыт и инсайты, не сухие гайды и не эзотерика.", "words_yes": ["самоценность", "игра", "позволь себе", "это не компромисс"], "words_no": ["волшебство", "гарантирую", "кликбейт"]}, "visual": {"colors": {"bg": "#4A0E1C", "bg_alt": "#F3E9E4", "text": "#FFFFFF", "text_on_light": "#2A1418", "accent": "#F4EC2A", "muted": "#C9A7A7", "card": "rgba(74,14,28,.72)", "accent_script": "#C0213A"}, "fonts": {"display": {"family": "Montserrat", "source": "google", "weight": 900, "case": "upper"}, "accent": {"family": "Marck Script", "source": "google", "weight": 400, "case": "normal"}, "body": {"family": "Montserrat", "source": "google", "weight": 700, "case": "normal"}}, "photo_style": "дом (светлое кресло, растение), машина, блейзеры; тёплый естественный свет", "layout": ["винно-бордовый градиент сверху и снизу кадра", "заголовок жирным широким капсом, ключевое слово жёлтым со свечением", "акцент рукописным курсивом (красный или белый)", "субтитры короткие, белые, жирные"], "shape": {"radius": "0", "glow": "жёлтое свечение на ключевом слове"}}, "channels": {"instagram": "https://instagram.com/o.hart.life_coach.ny", "cta_style": "кодовое слово в комментариях → воронка → сессия"}, "rules": {"compliance": "standard", "never": ["обещания «волшебства»", "эзотерический туман"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (24, $q${"identity": {"display_name": "Юлия", "role_line": "риелтор · Пенсильвания", "niche": "real_estate", "geo": "Пенсильвания, США", "language": "ru", "address": "вы", "voice_notes": "Спокойный деловой тон: факты о рынке и районах, проверка объекта, подводные камни при покупке.", "words_yes": ["а вы знали", "проверить", "история объекта", "статистика"], "words_no": ["гарантированный рост цены"]}, "visual": {"colors": {"bg": "#0F1B2D", "bg_alt": "#F5F5F2", "text": "#FFFFFF", "text_on_light": "#111111", "accent": "#FFFFFF", "muted": "#C7CFD8", "card": "rgba(15,27,45,.55)"}, "fonts": {"display": {"family": "Montserrat", "source": "google", "weight": 700, "case": "normal"}, "accent": {"family": "Montserrat", "source": "google", "weight": 800, "case": "normal"}, "body": {"family": "Montserrat", "source": "google", "weight": 300, "case": "normal"}}, "photo_style": "офис у окна с фото объектов; чёрный пиджак, белая блуза; дрон над пригородами и даунтауном", "layout": ["субтитры тонким белым, ключевые слова жирным белым", "эксперт в круглой мягкой виньетке поверх съёмки с дрона", "американские пригороды, закаты, улицы — как фон мысли"], "shape": {"radius": "50% для виньетки эксперта"}}, "channels": {"instagram": "https://instagram.com/julia_realtor_pennsylvania", "cta_style": "уточнить"}, "rules": {"compliance": "standard", "never": ["обещание доходности", "дискриминирующие формулировки о районах (Fair Housing)"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (28, $q${"identity": {"display_name": "Надія Сенева", "role_line": "Bastion Plus · інвестиції в нерухомість Болгарії з 2011", "niche": "real_estate", "geo": "Бургас, Несебр, Святий Влас, Сонячний Берег", "language": "uk", "address": "вы", "voice_notes": "Герой контенту — інвестиція, а не нерухомість. Короткі речення, міфи, порівняння, прості схеми. Доступний поріг входу, переуступка, юридичний супровід, без комісій для клієнта.", "words_yes": ["переуступка", "на етапі будівництва", "юридичний супровід", "прямі договори із забудовниками", "з 2011 року"], "words_no": ["гарантований дохід", "нерухомість для багатих", "суми не в євро"]}, "visual": {"colors": {"bg": "#1F6B6B", "bg_alt": "#F4F8F7", "text": "#FFFFFF", "text_on_light": "#123E40", "accent": "#A8F0D8", "muted": "#CFE3E0", "card": "rgba(31,107,107,.85)", "bg_dark": "#184F52"}, "fonts": {"display": {"family": "Oswald", "source": "google", "weight": 700, "case": "upper"}, "accent": {"family": "Great Vibes", "source": "google", "weight": 400, "case": "normal"}, "body": {"family": "Montserrat", "source": "google", "weight": 500, "case": "normal"}}, "photo_style": "світлий офіс з вікнами, біла блуза; на столі каталог і картка Bastion; будмайданчики, євро, об'єкти", "layout": ["заголовок вузьким білим капсом + підрядок звичайним шрифтом", "бірюзова смуга-градієнт внизу кадру", "нумерація пунктів «2.» великою цифрою + бірюзова плашка з текстом", "назва комплексу рукописним шрифтом + фото об'єкта", "ключові слова субтитрів у бірюзових плашках"], "shape": {"radius": "6px для плашок"}}, "channels": {"cta_style": "кодове слово, коментар або запит на підбір об'єкта"}, "rules": {"compliance": "standard", "never": ["гарантована прибутковість", "цифри не в євро"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (29, $q${"identity": {"display_name": "Million Miles", "role_line": "авто из Кореи · Андрей и Вениамин", "niche": "auto", "geo": "Корея → СНГ/ОАЭ", "language": "ru", "address": "ты", "voice_notes": "Познавательно, не витрина: истории марок, инженерия, споры «S-Class или 7-я». Уверенно, с лёгкой иронией.", "words_yes": ["легенда", "на самом деле", "думаешь, твой…"], "words_no": ["купи сейчас", "лучшая цена"]}, "visual": {"colors": {"bg": "#0B0B0C", "bg_alt": "#F4F1EA", "text": "#F3DDB0", "text_on_light": "#111111", "accent": "#C8102E", "muted": "#BDB3A0", "card": "rgba(0,0,0,.5)"}, "fonts": {"display": {"family": "Oswald", "source": "google", "weight": 700, "case": "upper"}, "accent": {"family": "Playfair Display", "source": "google", "weight": 700, "case": "normal"}, "body": {"family": "Montserrat", "source": "google", "weight": 700, "case": "normal"}}, "photo_style": "премиальные машины, салоны, шоурум; спикер снизу кадра — голубое поло в шоуруме или белое поло в салоне авто", "layout": ["сплит: сверху машина, снизу спикер", "субтитры в две строки тёплым кремовым: первая тоньше, вторая жирнее", "название марки крупным узким капсом, иногда красным («MERCEDES»)", "сравнения курсивом («S-Class or Series 7»)"], "shape": {"radius": "0"}}, "channels": {"instagram": "https://instagram.com/millionmileskr", "codeword": "АВТО", "cta_style": "пиши слово АВТО в комментариях"}, "rules": {"compliance": "standard", "never": [], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (31, $q${"identity": {"display_name": "Ярослав Иванов", "role_line": "контент-системы для бизнеса · EasyLife AI", "niche": "expert", "geo": "СНГ + США", "language": "ru", "address": "ты", "voice_notes": "Предприниматель, который построил систему и делится выводами. Уверенно, прямо, местами провокационно: ломать убеждения цифрами и кейсами. Продаём результат для бизнеса, не технологию.", "words_yes": ["контент-система", "на самом деле", "проблема не в…", "выигрывают не те, кто…"], "words_no": ["нейросеть/ИИ/аватар в первых 3 секундах", "на автопилоте", "мотивационные клише", "гарантирую"]}, "visual": {"colors": {"bg": "#070526", "bg_alt": "#F3F1FA", "text": "#FFFFFF", "text_on_light": "#070526", "accent": "#B6F500", "muted": "#A7A3C2", "card": "rgba(7,5,38,.72)"}, "fonts": {"display": {"family": "Unbounded", "source": "google", "weight": 800, "case": "normal"}, "accent": {"family": "Unbounded", "source": "google", "weight": 800, "case": "upper"}, "body": {"family": "Manrope", "source": "google", "weight": 600, "case": "normal"}}, "photo_style": "студия с неоновой фиолетово-синей подсветкой, тёмный лонгслив", "layout": ["хук-парадокс с цифрой в первом кадре", "ключевое слово лаймом", "пруф — скрин с цифрами в кадре"], "shape": {"radius": "14px"}}, "channels": {"instagram": "https://instagram.com/yaroslav.1vanov.ai", "telegram": "https://t.me/yaroslav1vanov", "cta_style": "кодовое слово в комментарий (не «смотри описание»)"}, "rules": {"compliance": "standard", "never": ["гарантии результата", "ИИ как главный герой"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (32, $q${"identity": {"display_name": "Casyn", "role_line": "legal help, simplified", "niche": "legal", "geo": "USA", "language": "en", "address": "вы", "voice_notes": "Plain-English legal explainers on everyday cases: firing, severance, insurance, rent. Calm, precise, deadline-driven.", "words_yes": ["in writing", "deadline", "your rights", "send this"], "words_no": ["guaranteed win", "legal advice (we are not your lawyer)"]}, "visual": {"colors": {"bg": "#0E1430", "bg_alt": "#F4F6FB", "text": "#FFFFFF", "text_on_light": "#0E1430", "accent": "#2C4EFC", "muted": "#8A93B2", "card": "#F4F6FB", "marker": "#FFE14D", "alert": "#E5484D"}, "fonts": {"display": {"family": "Inter", "source": "google", "weight": 800, "case": "upper"}, "accent": {"family": "Inter", "source": "google", "weight": 800, "case": "normal"}, "body": {"family": "Inter", "source": "google", "weight": 600, "case": "normal"}}, "photo_style": "аватар в студии; «лист дела» — бумага с жёлтым маркером", "layout": ["хук-заголовок обложки с 0:00, одна строка на жёлтом маркере", "документ с маркером на ключевом слове, аватар в кружке", "счётчик срока, чек-лист, шкала событий, экран Casyn"], "shape": {"radius": "12px", "documents_font": "Georgia"}}, "channels": {"instagram": "https://instagram.com/casyn.ai", "site": "https://casyn.ai", "cta_style": "уточнить: кодовое слово или ссылка"}, "rules": {"compliance": "standard", "never": ["обещание исхода дела", "подача как юридической консультации"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (33, $q${"identity": {"display_name": "Антон Чехов", "role_line": "Edeal · бизнес в США · Enrolled Agent", "niche": "finance", "geo": "США", "language": "ru", "address": "вы", "voice_notes": "Опытный CPA-друг: компетентный, прямой, невзволнованный. Широкая тема-открывашка (Опра, Kit Kat, Hummer) → мостик в налоги/бизнес → последствие с цифрой.", "words_yes": ["легально", "списать", "мой взгляд", "обычно", "в большинстве случаев"], "words_no": ["на автопилоте", "контент-завод", "гарантированная экономия", "вас посадят"]}, "visual": {"colors": {"bg": "#0F1A3A", "bg_alt": "#F5F6F8", "text": "#FFFFFF", "text_on_light": "#0F1A3A", "accent": "#FFD200", "muted": "#AEB5C6", "card": "#1E3A8A", "card_alt": "#8B1E1E"}, "fonts": {"display": {"family": "Oswald", "source": "google", "weight": 700, "case": "upper"}, "accent": {"family": "Oswald", "source": "google", "weight": 700, "case": "upper"}, "body": {"family": "Montserrat", "source": "google", "weight": 800, "case": "normal"}}, "photo_style": "сюжетный б-ролл: сгенерированные сцены героя истории, кадры знаменитостей, скриншоты сайтов; Антон на улице/террасе", "layout": ["ключевые фразы в тёмно-синих или тёмно-красных плашках", "хук-заголовок узким капсом, «лазейки» жёлтым в кавычках", "документальные вставки: скрин закона/сайта с плашкой-пояснением"], "shape": {"radius": "4px"}}, "channels": {"site": "https://edeal.ai", "telegram": "https://t.me/edeal_ai", "cta_style": "вопрос-подъёб в комментарии + кодовое слово для горячих"}, "rules": {"compliance": "standard", "never": ["категоричные обещания по налогам", "драматизация страха перед IRS"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (34, $q${"identity": {"display_name": "Million Miles", "role_line": "cars from Japan", "niche": "auto", "geo": "Japan → worldwide", "language": "en", "address": "ты", "voice_notes": "Car explainers for a broad audience: types of doors, turbo vs supercharger, badges. Friendly, fast, visual.", "words_yes": ["here are all the", "this is a", "types of"], "words_no": []}, "visual": {"colors": {"bg": "#0B0B0C", "bg_alt": "#FFFFFF", "text": "#FFFFFF", "text_on_light": "#111111", "accent": "#F2C230", "muted": "#B9B9B9", "card": "rgba(0,0,0,.45)"}, "fonts": {"display": {"family": "Oswald", "source": "google", "weight": 700, "case": "normal"}, "accent": {"family": "Montserrat", "source": "google", "weight": 900, "case": "upper"}, "body": {"family": "Montserrat", "source": "google", "weight": 800, "case": "normal"}}, "photo_style": "молодой спикер в белой футболке, салон авто или гараж; сверху машины и детали", "layout": ["сплит: сверху машина/деталь, снизу спикер", "серийный заголовок жёлто-золотым («types of car doors») + вордмарк MILLION MILES", "подписи-ярлыки курсивным капсом на белом («TURBO C», «SEDAN»)", "субтитры белые жирные с тенью"], "shape": {"radius": "0"}}, "channels": {"instagram": "https://instagram.com/millionmiles.jp", "cta_style": "уточнить"}, "rules": {"compliance": "standard", "never": [], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (35, $q${"identity": {"display_name": "Dr. Marina Gafanovich", "role_line": "Internist · Concierge Privilege", "niche": "medical", "geo": "Sunny Isles Beach, FL · New York", "language": "en", "address": "вы", "voice_notes": "Calm, warm authority of a 20+ year internist. Explains the healthcare system and bills in plain words; honest about what's not needed.", "words_yes": ["documented", "practicing internist", "FDA-approved", "your case"], "words_no": ["compounded as a recommendation", "cure", "guaranteed"]}, "visual": {"colors": {"bg": "#2A1D16", "bg_alt": "#F7F3EE", "text": "#FFFFFF", "text_on_light": "#1E1E1E", "accent": "#D9B84A", "muted": "#BFB2A3", "card": "rgba(42,29,22,.6)", "coat_blue": "#1F4FD1"}, "fonts": {"display": {"family": "Cormorant Garamond", "source": "google", "weight": 500, "case": "normal"}, "accent": {"family": "Poppins", "source": "google", "weight": 600, "case": "normal"}, "body": {"family": "Poppins", "source": "google", "weight": 500, "case": "normal"}}, "photo_style": "тёплый кабинет: кирпичная стена, лампа, тёмное платье — или белый халат с синим верхом", "layout": ["заголовок тонкой элегантной антиквой в 2–3 строки", "субтитры мелкие строчные белые, ключевое слово горчичным", "крупные полупрозрачные цифры для пунктов («2», «5»)", "бытовой б-ролл: счёт за лечение, витамины, капельница"], "shape": {"radius": "12px"}}, "channels": {"instagram": "https://instagram.com/mymiamidoctor", "site": "https://mymiadoctor.com", "cta_style": "уточнить через агентство"}, "rules": {"compliance": "medical_us", "never": ["рекомендация compounded-препаратов", "обещания результата лечения", "данные пациентов"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (36, $q${"identity": {"display_name": "Ігор", "role_line": "стоматолог · імплантація і протезування", "niche": "medical", "geo": "Україна", "language": "uk", "address": "вы", "voice_notes": "Лікар спокійно знімає страх: чи боляче, скільки триває, знімне чи на імплантах. Кейси пацієнтів і прості 3D-пояснення.", "words_yes": ["без болю", "на імплантах", "підкажу", "ваш випадок"], "words_no": ["гарантую", "назавжди"]}, "visual": {"colors": {"bg": "#1D2B44", "bg_alt": "#F5F7FB", "text": "#FFFFFF", "text_on_light": "#1D2B44", "accent": "#E0A23A", "muted": "#B7C0D0", "card": "#FFFFFF", "sub_text": "#3B7BD8", "sub_text_alt": "#8E44D9"}, "fonts": {"display": {"family": "Nunito", "source": "google", "weight": 900, "case": "normal"}, "accent": {"family": "Nunito", "source": "google", "weight": 900, "case": "normal"}, "body": {"family": "Nunito", "source": "google", "weight": 800, "case": "normal"}}, "photo_style": "кабінет з КТ-моніторами; темний скраб або синя футболка з принтом зуба", "layout": ["хук «драбинкою» зі слів різного розміру на грудях: білий + гірчичний", "субтитри в білих заокруглених плашках синім або фіолетовим текстом", "3D-моделі щелеп і імплантів, числа «3 → 0» поруч із моделями"], "shape": {"radius": "14px для плашок субтитрів"}}, "channels": {"instagram": "https://instagram.com/3dstomatolog", "cta_style": "Напишіть кодове слово («ПРОТЕЗ», «КОРОНКА») — підкажу"}, "rules": {"compliance": "medical", "never": ["гарантія результату", "фото пацієнтів без згоди"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (37, $q${"identity": {"display_name": "Albena Ivanova", "role_line": "travel advisor · Foreign Affair", "niche": "travel", "geo": "Charlotte, NC", "language": "en", "address": "ты", "voice_notes": "Insider travel tips from an advisor: myths, secrets, money-savers. Warm, energetic, personal («I'll answer you personally»).", "words_yes": ["secrets", "never", "lock the price", "message me"], "words_no": []}, "visual": {"colors": {"bg": "#141414", "bg_alt": "#F2EFEA", "text": "#FFFFFF", "text_on_light": "#111111", "accent": "#F7D117", "muted": "#BDBDBD", "card": "rgba(0,0,0,.5)", "alert": "#E0192B"}, "fonts": {"display": {"family": "Montserrat", "source": "google", "weight": 900, "case": "upper"}, "accent": {"family": "Montserrat", "source": "google", "weight": 900, "case": "upper"}, "body": {"family": "Montserrat", "source": "google", "weight": 700, "case": "normal"}}, "photo_style": "она в белой куртке в студии или в ярком платье на природе; круизы, аэропорты, города с дрона", "layout": ["заголовок жирным капсом жёлтым + подзаголовок белым", "запрет/опасность красным («NEVER»)", "текстура мятой бумаги для списков и приложений", "субтитры белые, ключевые слова жёлтым"], "shape": {"radius": "0"}}, "channels": {"instagram": "https://instagram.com/foreignaffair2026", "cta_style": "Message me · Tell me in the comments — I'll answer personally"}, "rules": {"compliance": "standard", "never": [], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (38, $q${"identity": {"display_name": "SVEKA Design", "role_line": "архитектура и интерьеры с 2012 · Дубай, Киев", "niche": "design", "geo": "Дубай · Киев · Европа", "language": "ru", "address": "вы", "voice_notes": "Студия с 13 годами и 500+ проектами, которая первой поставила ИИ на поток. Красивое видео о дизайне без лишнего; аватар — ведущая рубрики, мысль несёт текст.", "words_yes": ["completed project", "500 проектов", "с 2012 года"], "words_no": ["рисуем нейросетью", "дёшево"]}, "visual": {"colors": {"bg": "#0B0B0B", "bg_alt": "#EDE9E3", "text": "#FFFFFF", "text_on_light": "#1A1A1A", "accent": "#C8B79E", "muted": "#9D978E", "card": "rgba(11,11,11,.6)"}, "fonts": {"display": {"family": "Montserrat", "source": "google", "weight": 600, "case": "upper"}, "accent": {"family": "Cormorant Garamond", "source": "google", "weight": 500, "case": "normal"}, "body": {"family": "Montserrat", "source": "google", "weight": 400, "case": "normal"}}, "photo_style": "премиальные интерьеры в нейтральной бежево-графитовой гамме; Светлана в чёрном костюме, мягкий свет", "layout": ["крупный титр сверху тонким разреженным капсом («COMPLETED PROJECT / TARYAN TOWERS»)", "подпись DESIGN BY SVEKA", "минимум текста, никаких цветных плашек", "аватар: одна мизансцена (кресло, тёмный интерьер), 6–9 секунд, говорит текст"], "shape": {"radius": "0", "tracking": "широкая разрядка у капса"}}, "channels": {"instagram": "https://instagram.com/sveka_design", "site": "https://www.svekadesign.com.ua", "cta_style": "уточнить"}, "rules": {"compliance": "standard", "never": ["виллы, сгенерированные с нуля, выдаваемые за проекты"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (39, $q${"identity": {"display_name": "Lash Couture", "role_line": "eyelash extension studio · Brooklyn", "niche": "beauty", "geo": "130 Brighton Beach Ave, Brooklyn, NY", "language": "en", "address": "ты", "voice_notes": "Уточнить — роликов в CRM пока нет. По профилю: люксовая студия, акцент на мастерах и крупных планах ресниц.", "words_yes": ["book now", "lash lift", "our artistry"], "words_no": []}, "visual": {"colors": {"bg": "#111111", "bg_alt": "#FFFFFF", "text": "#FFFFFF", "text_on_light": "#111111", "accent": "#C9A45C", "muted": "#B8B0A2", "card": "rgba(255,255,255,.85)"}, "fonts": {"display": {"family": "Playfair Display", "source": "google", "weight": 700, "case": "normal"}, "accent": {"family": "Great Vibes", "source": "google", "weight": 400, "case": "normal"}, "body": {"family": "Montserrat", "source": "google", "weight": 500, "case": "normal"}}, "photo_style": "макро ресниц, золотой декор, белый мрамор; мастера в чёрном", "layout": ["логотип золотым рукописным на белом", "минимум текста, макро-кадры", "имена мастеров в хайлайтах"], "shape": {"radius": "999px для хайлайтов"}}, "channels": {"instagram": "https://instagram.com/lash_couture_corp", "site": "https://linktr.ee/lashcouture", "whatsapp": "+1 917-720-8555", "cta_style": "Book now · $30 deposit required"}, "rules": {"compliance": "standard", "never": [], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (40, $q${"identity": {"display_name": "Laccura Medical", "role_line": "functional medicine · Lincolnwood, IL", "niche": "medical", "geo": "7350 N. Cicero Ave, Lincolnwood, IL", "language": "en", "address": "вы", "voice_notes": "Inna Hoffman (APRN) и Oksana Krysko (RN): гормоны, анализы крови, вес, энергия. Спокойная экспертиза, «разберём ВАШ случай» — формат по мотивам dr.panch.", "words_yes": ["your blood test", "hormones", "root cause", "your case"], "words_no": ["cure", "guaranteed"]}, "visual": {"colors": {"bg": "#1E2233", "bg_alt": "#F6F3EE", "text": "#FFFFFF", "text_on_light": "#1E2233", "accent": "#D8B25A", "muted": "#B9B3A8", "card": "rgba(30,34,51,.55)", "scrubs": "#2B2F5C", "sage": "#A7B79E"}, "fonts": {"display": {"family": "Montserrat", "source": "google", "weight": 300, "case": "upper"}, "accent": {"family": "Great Vibes", "source": "google", "weight": 400, "case": "normal"}, "body": {"family": "Montserrat", "source": "google", "weight": 500, "case": "normal"}}, "photo_style": "клиника: тёплое дерево, золотые полки; врачи в тёмно-синих скрабах; лаборатория, пробирки", "layout": ["заголовок тонким белым капсом + «PART 2»", "акцент золотым рукописным («What labs»)", "субтитры мелкие белые", "3D-анатомия и лабораторный б-ролл"], "shape": {"radius": "0"}}, "channels": {"instagram": "https://instagram.com/laccuramedical", "site": "https://laccura.com/?utm_campaign=lincolnwood", "cta_style": "DM-кодовое слово («DM WELLNESS»)"}, "rules": {"compliance": "medical_us", "never": ["обещание результата", "до/после без подписи протокола", "прямые формулировки об интимном здоровье (Meta банит — история блокировок)"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_brand (client_id, kit, version) values (41, $q${"identity": {"display_name": "Laccura MedSpa", "role_line": "aesthetics · Highland Park, IL", "niche": "medical", "geo": "1729 Green Bay Rd, Highland Park, IL", "language": "en", "address": "вы", "voice_notes": "Эстетика: Botox, филлеры, Morpheus8, лазеры. Лёгкий тон, разборы звёзд («What does Hailey Bieber love?»), протокол всегда подписан.", "words_yes": ["your glow", "protocol", "first sign of aging"], "words_no": ["guaranteed", "no downtime (если это не так)"]}, "visual": {"colors": {"bg": "#1E1A18", "bg_alt": "#F4EEE6", "text": "#FFFFFF", "text_on_light": "#2A211C", "accent": "#7A1F1F", "muted": "#BDB2A5", "card": "rgba(30,26,24,.55)", "gold": "#C9A45C", "sage": "#A7B79E"}, "fonts": {"display": {"family": "Montserrat", "source": "google", "weight": 800, "case": "upper"}, "accent": {"family": "Great Vibes", "source": "google", "weight": 400, "case": "normal"}, "body": {"family": "Montserrat", "source": "google", "weight": 500, "case": "normal"}}, "photo_style": "кабинет с золотыми полками, процедуры крупно; врачи в тёмно-синих скрабах", "layout": ["заголовок белым жирным курсивным капсом с тенью", "рукописные белые акценты поверх кадра", "хайлайты — бордо с кремовой антиквой (LAB TESTS, MENU)", "до/после с подписью протокола («3 Morpheus8 + 3 Lumecca»)"], "shape": {"radius": "0"}}, "channels": {"instagram": "https://instagram.com/laccuramedspa", "site": "https://laccura.com/?utm_campaign=highlandpark", "cta_style": "DM-кодовое слово"}, "rules": {"compliance": "medical_us", "never": ["обещание результата", "до/после без подписи протокола", "прямые формулировки об интимном здоровье (Meta банит — история блокировок)"], "consent_required_for_faces": true}, "meta": {"filled_by": "Claude, 29.09.2026", "source": "последние ролики в CRM + Instagram + аудиты", "status": "черновик — проверить тимлиду"}}$q$::jsonb, 1)
on conflict (client_id) do nothing;

insert into public.client_documents (client_id, kind, title, body, version, is_current, note, author_name)
select 14, 'strategy', 'Контент-стратегия', $q$ФОРМАТ (разобран по 39 роликам, 05.09.2026)
• TikTok у хирурга в 3,4 раза сильнее Instagram — ведём обе сети.
• Обложка: сплит — объект разговора по краям, врач в центре в одной и той же одежде; жирный белый гротеск капсом 2–3 строки. Заголовок — вопрос или утверждение, никогда не название процедуры.
• Хук — заявление, а не вопрос (×4,6 против ×0,3), с отрицанием очевидного, дальше масштаб на зрителя.
• 5 архетипов: A «посмотрите на это — а теперь на это» ×4,6 · B селебрити + врач ОТКАЗЫВАЕТ ×4,3 · C эволюция лица звезды ×2,3 · D «как врач не советую своим близким» · E классификация ЗРИТЕЛЯ («ваш тип старения»).
• Проваливается: справочники форм, ярлыки-тренды, туториалы, ролики короче 25 секунд.
• CTA: не «запишитесь», а «разберём ВАШ случай»: в IG «+» в комментариях, в TikTok — в директ.$q$, 1, true, $q$Черновик собран Claude 29.09 по нашим аудитам и разборам — проверить и дополнить$q$, 'Claude'
where not exists (select 1 from public.client_documents where client_id = 14 and kind = 'strategy' and is_current);

insert into public.client_documents (client_id, kind, title, body, version, is_current, note, author_name)
select 21, 'strategy', 'Контент-стратегия', $q$ПОЗИЦИЯ: продукт — ТРАНСФОРМАЦИОННАЯ ИГРА, а не гайды (пивот).
• Сегмент: деньги + самоценность у женщин.
• Контент: живой опыт и инсайты из игр, книги и сцены из жизни как повод, «я тоже так делала».
• Конкурент для ориентира — «Игры ЛиЛу».
• CTA: кодовое слово в комментариях → воронка → продажа сессии голосом.$q$, 1, true, $q$Черновик собран Claude 29.09 по нашим аудитам и разборам — проверить и дополнить$q$, 'Claude'
where not exists (select 1 from public.client_documents where client_id = 21 and kind = 'strategy' and is_current);

insert into public.client_documents (client_id, kind, title, body, version, is_current, note, author_name)
select 31, 'strategy', 'Контент-стратегия', $q$ЦЕЛЬ: лиды в EasyLife ($1,5–5,4k), не личный бренд ради бренда.
• 100% ИИ-аватар — это одновременно доказательство продукта.
• Фильтр платёжеспособности стоит в ХУКЕ: без слов «нейросеть/ИИ/аватар» в первых 3 секундах.
• 5 рубрик: сериал «НАС НЕТ» (флагман) · диагноз чужого аккаунта (главный генератор входящих) · пруф цифрами со скрина · anti-hype · механика конвейера.
• Ритм: 6 Reels + 1 карусель в неделю, 3–5 сторис в день (живой слой).
• Правило: 5 роликов одного типа с удержанием 3 сек < 40% → тип закрываем.
• CTA — кодовое слово в комментарий, не «смотри описание».$q$, 1, true, $q$Черновик собран Claude 29.09 по нашим аудитам и разборам — проверить и дополнить$q$, 'Claude'
where not exists (select 1 from public.client_documents where client_id = 31 and kind = 'strategy' and is_current);

insert into public.client_documents (client_id, kind, title, body, version, is_current, note, author_name)
select 32, 'strategy', 'Контент-стратегия', $q$ФОРМАТ «ПАПКА ДЕЛА» (разбор 12 роликов @casyn.ai, 28.09.2026)
• Было: 60–589 просмотров; заголовок только на обложке, мелкие субтитры, 5 разных шаблонов и 5 разных призывов.
• Стало: хук-заголовок обложки с 0:00 + приближение аватара → документ с жёлтым маркером на ключевом слове → счётчик срока / чек-лист / шкала событий → экран Casyn → один призыв.
• Темы: everyday legal — увольнение, severance, страховая, иммиграция, аренда, развод. НЕ personal injury.
• Решить: CTA — кодовое слово или ссылка.$q$, 1, true, $q$Черновик собран Claude 29.09 по нашим аудитам и разборам — проверить и дополнить$q$, 'Claude'
where not exists (select 1 from public.client_documents where client_id = 32 and kind = 'strategy' and is_current);

insert into public.client_documents (client_id, kind, title, body, version, is_current, note, author_name)
select 33, 'strategy', 'Контент-стратегия', $q$ПОЗИЦИЯ: опытный CPA-друг. Лицо — Антон Чехов (Enrolled Agent), Edeal с 2019, 1700+ клиентов.
• ДИРЕКТИВА КЛИЕНТА (21.08): очень широкие темы, интересные всем (звёзды, бренды, курьёзы) → мостик в бизнес и налоги США. Узкие темы про LLC/налоги «соберут 20 просмотров».
• Каркас (85–95 сек): хук-факт → фактура → механика → последствие с цифрой → мостик → CTA. Именованный персонаж с нелепой деталью доживает до финала.
• CTA двухуровневый: вопрос-подъёб в комментарии + кодовое слово для горячих.
• Запрет: упаковка «контент-завод на автопилоте» — Антона на этом чуть не развели, он публично это разоблачал.
• Все цифры и нормы подтверждает Антон до съёмки.$q$, 1, true, $q$Черновик собран Claude 29.09 по нашим аудитам и разборам — проверить и дополнить$q$, 'Claude'
where not exists (select 1 from public.client_documents where client_id = 33 and kind = 'strategy' and is_current);

insert into public.client_documents (client_id, kind, title, body, version, is_current, note, author_name)
select 35, 'strategy', 'Контент-стратегия', $q$ПОЗИЦИЯ: Concierge Privilege — терапевт 20+ лет (Weill Cornell / NY-Presbyterian), Майами и Нью-Йорк. Работаем через агентство.
• Вывод исследования (12.08): concierge / pre-op / I-693 — потолок 27–87 тыс. просмотров. Главная вирусная вена — «система здравоохранения США»: счета, страховки, что врач не скажет.
• Weight management — только FDA-одобренные GLP-1, принципиально НЕ compounded.
• Контент-банк: подкаст SUPERHUMANS (сторителлинг «я ждала тебя четыре года», иммигрантская история).$q$, 1, true, $q$Черновик собран Claude 29.09 по нашим аудитам и разборам — проверить и дополнить$q$, 'Claude'
where not exists (select 1 from public.client_documents where client_id = 35 and kind = 'strategy' and is_current);

insert into public.client_documents (client_id, kind, title, body, version, is_current, note, author_name)
select 38, 'strategy', 'Контент-стратегия', $q$ПОЗИЦИЯ: не «рисуем нейросетью», а «студия с 13 годами и 500+ проектами, которая первой поставила ИИ на поток».
• Контент-модель по 4 эталонам: @yodezeen_architects и @trush.design — красивое видео о дизайне (~55%); @victoria.stekl и @aleksandrabos.studio — под ИИ-аватар и подачу (~35%).
• Разница YODEZEEN (медиана 43,8 тыс.) и TRUSH (7,7 тыс.) при одинаковом визуале — ПОВОД: необычный носитель, премьера, награда, цифра.
• Аватар: одна мизансцена, крупный титр сверху, мысль несёт текст, 6–9 секунд.
• Сейчас: 29,3 тыс. подписчиков, медиана Reels 2 200. Цель по KPI — 12 000.$q$, 1, true, $q$Черновик собран Claude 29.09 по нашим аудитам и разборам — проверить и дополнить$q$, 'Claude'
where not exists (select 1 from public.client_documents where client_id = 38 and kind = 'strategy' and is_current);

insert into public.client_documents (client_id, kind, title, body, version, is_current, note, author_name)
select 40, 'strategy', 'Контент-стратегия', $q$ПОЗИЦИЯ: смена подрядчика, а не холодный старт. Разделение Medical/MedSpa осознанное.
• Факт из их кабинета (август): Medical — лид на 8 250 просмотров, MedSpa — на 45 167. Medical в 5,5 раза эффективнее → перевес в гормоны, вес, анализы.
• Формат — по мотивам dr.panch: «разбор звезды», два врача-женщины (можно диалог), обещание «разберём ваш случай».
• Референсы клиента: @thenovuscenter_ (темы + DM WELLNESS), @lifesculpt_naperville (протокол под до/после).
• КОМПЛАЕНС: Medical банили 13.05.2026 — интимное здоровье, GLP-1, пептиды подаём максимально аккуратно.
• Боли клиента: результат 65% от ожиданий, ошибки в английском, неточный монтаж, задержки.$q$, 1, true, $q$Черновик собран Claude 29.09 по нашим аудитам и разборам — проверить и дополнить$q$, 'Claude'
where not exists (select 1 from public.client_documents where client_id = 40 and kind = 'strategy' and is_current);

insert into public.client_documents (client_id, kind, title, body, version, is_current, note, author_name)
select 15, 'strategy', 'Контент-стратегия', $q$ФОРМАТ (разобран по 39 роликам, 05.09.2026)
• TikTok у хирурга в 3,4 раза сильнее Instagram — ведём обе сети.
• Обложка: сплит — объект разговора по краям, врач в центре в одной и той же одежде; жирный белый гротеск капсом 2–3 строки. Заголовок — вопрос или утверждение, никогда не название процедуры.
• Хук — заявление, а не вопрос (×4,6 против ×0,3), с отрицанием очевидного, дальше масштаб на зрителя.
• 5 архетипов: A «посмотрите на это — а теперь на это» ×4,6 · B селебрити + врач ОТКАЗЫВАЕТ ×4,3 · C эволюция лица звезды ×2,3 · D «как врач не советую своим близким» · E классификация ЗРИТЕЛЯ («ваш тип старения»).
• Проваливается: справочники форм, ярлыки-тренды, туториалы, ролики короче 25 секунд.
• CTA: не «запишитесь», а «разберём ВАШ случай»: в IG «+» в комментариях, в TikTok — в директ.$q$, 1, true, $q$Черновик собран Claude 29.09 по нашим аудитам и разборам — проверить и дополнить$q$, 'Claude'
where not exists (select 1 from public.client_documents where client_id = 15 and kind = 'strategy' and is_current);

insert into public.client_documents (client_id, kind, title, body, version, is_current, note, author_name)
select 41, 'strategy', 'Контент-стратегия', $q$ПОЗИЦИЯ: смена подрядчика, а не холодный старт. Разделение Medical/MedSpa осознанное.
• Факт из их кабинета (август): Medical — лид на 8 250 просмотров, MedSpa — на 45 167. Medical в 5,5 раза эффективнее → перевес в гормоны, вес, анализы.
• Формат — по мотивам dr.panch: «разбор звезды», два врача-женщины (можно диалог), обещание «разберём ваш случай».
• Референсы клиента: @thenovuscenter_ (темы + DM WELLNESS), @lifesculpt_naperville (протокол под до/после).
• КОМПЛАЕНС: Medical банили 13.05.2026 — интимное здоровье, GLP-1, пептиды подаём максимально аккуратно.
• Боли клиента: результат 65% от ожиданий, ошибки в английском, неточный монтаж, задержки.$q$, 1, true, $q$Черновик собран Claude 29.09 по нашим аудитам и разборам — проверить и дополнить$q$, 'Claude'
where not exists (select 1 from public.client_documents where client_id = 41 and kind = 'strategy' and is_current);

-- Проверка
select c.id, c.name, (b.client_id is not null) as "бренд",
       exists (select 1 from public.client_documents d where d.client_id = c.id and d.kind = 'strategy' and d.is_current) as "стратегия"
from public.clients c left join public.client_brand b on b.client_id = c.id
where c.stage = 'active' order by c.id;
